### ISSUE TITLE
Need a description of the project

### ISSUE THREAD

**Issue by joebb97** [ThePrimeagen/vim-with-me#17]
I've heard Prime mention this project a few times but have no idea what it does. I'd do a PR to add a README but that's a bit of a Catch 22.

Anything helps!

**Comment by joebb97** [comment]
Realizing now that maybe this is an older version of https://github.com/ThePrimeagen/vim-royale ?

If so maybe mark this project as an archive and link to the new one? Sorry if I'm off base here.

**Comment by Alan-MQ** [comment]
yeah, I think a readme file would be really great~~

**Comment by ThePrimeagen** [comment]
at some very later point.  i _intentionally_ do not want people using this.  the interface is in rapid change right now

yes this opens up the door for vim royale
