### ISSUE TITLE
im starving

### ISSUE THREAD

**Issue by WarrenBuffering** [ThePrimeagen/vim-with-me#26]
i left the mayo out yesterday and had to throw it out and the only thing in the fridge to eat right now is deli roast beef and i have the bread too but i dont want to make a sandwich without mayo that sounds disgusting

TIA

**Comment by WarrenBuffering** [comment]
.

**Comment by ThePrimeagen** [comment]
Speaking of speaking of crises, I need to get pretzels

**Comment by ThePrimeagen** [comment]
Shit up

**Comment by WarrenBuffering** [comment]
bump. im also seeing this issue

**Comment by iliaamiri** [comment]
> bump. im also seeing this issue

have you tried restarting your refrigerator?

**Comment by aleury** [comment]
cud you add support for vs code? thx.

**Comment by Sidd-underscore** [comment]
Looks IE 11 is having issues as well

**Comment by Lalanthawi** [comment]
have you tried turning it off and on again?

**Comment by taigrr** [comment]
I did! See #136
